language: java
jdk:
- oraclejdk8
after_success:
  - mvn clean test jacoco:report coveralls:report
deploy:
  provider: heroku
  api_key:
    secure:
    Jjg0H1PQluenW0CwWz2xiUABxjybwYFLDMy/xgz2qClaPHS5Kw0znJU0ElZvfWmAkzkrN4Y0gls2ikk33Zf46hm4KnSZCUre3aW5b91TpEoQGnq1tv7kfkLl+wz8brV8YyyYIbwx97zdPcoMgstY8qbhnyxyqbBPMnp9EeTFPg2bGV6s27fc/T+HBdViDypWoQwonW1QdsA4qQ/WdrHKeS+E1NLSSH2fab/mcHdccNYXktQvfi1lmIgeo/tf7xSNUCmJX8LjPwVTgthrggwXP/5iq2Jp1RHMeYJcUOARpNCVpzxyGwSkYgfnB+rV47CMNS5oLuQ1AdX84TOYCXLH3sDZhDkwyuerNwN2hV+Uwhg+4t6i70XwHH6jL6GgP0QZEZvbKLe9MG4RoSZUOJEUG2HMCaGHpAST1PlNWiWn6f9oVz1KNpCCGZXTnGKztHJwxPJnM3vTVws6w4FHr16m+S+RCM6MYX5g9BTL06LYRd3P9rb9zeUUter++oLw4Oq82MbxEM7wvPVrN/yGdozXkogtFEmM8dQYvWDo2Scms913f3LDmy5GjMPGI9bXfUjSpzppVUjDW5xmzJVZywWow7XZo9h8wYCH6lBz4Rhb2RENzr84nmIDx7WTlPQc1YoQAqj03mhX7d5Y7BFhD+7ogA5TAx8fewBsPA3SvSdzK1U=
  app: dropwizardheroku-webgateway
  on:
    repo: damorton/dropwizardheroku-webgateway
