language: java
jdk:
- oraclejdk8
after_success:
- ./gradlew test jacocoTestReport coveralls
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: IYyCyMQXZWTRUmPkaLs2ifV/8tbHNDPMWF9nhZZFVYDkWUpDTzfAZewVSpe91q9Mv9IpxAts9VhOBCQ2Hlpot4MNX0lkLMJAqG7IDRISBit4R4r/ACmwvl4bAtMWi65CKrduOS3k630ARoAnK76cQZwEFhYu/00GudlbBHQIP2PiEOAy70ous9Ox5W4B5KLOFDqbIf7cAU1jnBMCwLK0ai/s3naqfoZGqrU9RzB6KGq0s15cxEvPsDilpONzF++9iUd4uMlvRO0rH8PgfEG+SB18v+yH1cpCgTqsF0b/rgOjr2duZOV7rHkeX1ZRAG08j9aJElEzACa3VOd4PeDHO0CKQr6yN2FCUIEiFyZdVRHhrllWHWCitIJY4sCvsRURWmSxhWcg+AFfCK14dEYwn2Ad2IVvtIY6qtSsSQ16Q32TCWs2OD4iHJjIHG18c9fwI1pun5U+NsPMMimj/rP3Vl8sFN7lWzoh0YDH135L7AeX2PovxjHYupirrN44ugX+zZRQapPKC2GZxQHiEDFPYzySgPho6WnxtVMve/BA7xUTS4sF+cBOJNgvjX/Db3JHxKaII8mqsCLdygAPZx8wQOCdRbSvqk4kDUV52f80OhE3ldlXFgxgRYtS/1lrBsjdH4+W9U7/HA75ZP/lJ5abgfuODkDMqk/emi7ARMU5v8c=
  app: lovat
  on:
    repo: damorton/lovat
notifications:
  email:
    on_success: never
    on_failure: always
