language: java
jdk:
- oraclejdk8
after_success:
- ./gradlew test jacocoTestReport coveralls
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: paEr+8m7K4qn0as8MfAWhkm3AVQ8+GprlMaTG+srjn36AUp/gEXjGNM9+fEOu5Cs9NSKrRb69MMtGZxnRJrrC1WmKcVEg3Ycv+OdV6NyW28hv//mJny8iRt/E6ZJH0hZMzwnKoucPfmstyGU56UCEAee3zW1iN96QFXWKXbt3dTObxHY1twhIWcOVUbppq1sCNJT7i79JOlPwEpV021vb/+touz3XW6HiycKDT5mdvij2cey6d6tzkib6sHr+7uii7mWKc60fP5B0Ltbisc7Ei/d4t1jylC5Gy9JFhJqQjkVrD8jfWXDsoPWH7hyKxZwrTLhXEXRTpf1Ifj+qgDqtwFiLTvDdtHTDJ/yUb09g3fNby1ns4tfiXdFf2cR5Meh6kISrI3Kw4OWewoP+3R7ueas6GQuhq9EmbCK+4yif0jUDI1LiY38BH8teU5kC0Jt86CmVR1PqEbJTrvFAFwj3Z8eRlJeWgbD9mSxTwHwf30Jz4y7U2xmYF+/uyXP+eW3YpV0NfhXZDu21yulFDKUcMkoA9fuULMHPdF6yjxV8UhjoEoF99ZM5+4aAiBc4T3hcv+vIIXLfWXlOUiwKRaXiOBURmV0uSr7JsnZkYIgiAnyGzGwCUVDUqsVef/EooobY9Em7zgupQ++7SorhSkHKrgb+09B5ytu/b4N+0vT53E=
  app: lovat
  on:
    repo: damorton/lovat
notifications:
  email:
    on_success: never
    on_failure: always
